server:
  port : 8084

questionnaire-service:
  url: http://localhost:8082
  answer-end-point: /v1/question/answer

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 3
        max-concurrency: 10


exam.result.queue-name: basirhat.exam.result.queue

no_of_questions_per_exam: 5
passing_score: 60.0